# Generated by Django 3.1.1 on 2021-02-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='creadted',
            new_name='created',
        ),
    ]
